#!/bin/sh
# ------------------------------------------------------------
# Convert the vhdl code to verilog

TOP="ring_oscillator"
V_OUT_NAME="RTL/verilog/$TOP.v"


# TODO explain the args
# 1 - take all the vhdl files and store them locally in .cf file

#ghdl --clean
#ghdl -i --work=unisim unisims/*.vhd
#ghdl -i --work=unisim unisims/primitive/*.vhd
#ghdl -i RTL/vhdl/ring_oscillator.vhd
#ghdl -m -g -Punisim --warn-unused --ieee=synopsys ring_oscillator

ghdl --clean
ghdl -i --std=08 --work=unisim unisims/*.vhd
ghdl -i --std=08 --work=unisim unisims/primitive/*.vhd
ghdl -i --std=08 --work=unisim RTL/vhdl/ring_oscillator.vhd

ghdl -m --std=08 --warn-unused --work=unisim $TOP
ghdl synth --std=08 --work=unisim -Pbuild --out=verilog $TOP > $V_OUT_NAME


# ------------------------------------------------------------
# Process the code in Yosys to create JSON file

#yosys -s flow_puf/yosys.ys
yosys -p "
read_verilog RTL/verilog/$TOP.v;
show -format svg -prefix my_design_graph_before ring_oscillator;
synth -top ring_oscillator;
write_json ring_oscillator.json;
show -format svg -prefix my_design_graphafter ring_oscillator;
"
# usage of -p command to put all commands separated with ";"

# ------------------------------------------------------------
# Process the JSON in Nextpnr-Xilinx to create FASM file


# Generate binary file for xc7s50csga324-1
#don't forget to do git submodule update --recursive --remote
#python3 ./xilinx/python/bbaexport.py --device xc7s50csga324-1 --bba xilinx/xc7s50csga324-1.bba
#./bba/bbasm --l xilinx/xc7s50csga324-1.bba xilinx/xc7s50csga324-1.bin

# --json   -> input file
# --router -> way to ordonance place and route

# Specific to the architecture
# --chipdb ->  xc7s50csga324-1.bin      (/home/adrien/nextpnr-xilinx/xilinx/)
# --xdc    ->  xdc/xc7s50csga324-1.xdc  TODO constraint file
# --fasm   ->                           TODO check if needed ?
# --device ->  xc7s50csga324-1

#

#================================================
# Routing with nextpnr-xilinx (experimental)
#================================================


CHIPDB ?= /home/adrien/nextpnr-xilinx/xilinx/xc7s50csga324-1.bin
FILENAME_NETLIST = ro_puf.json
FILENAME_ROUTED  = ro_puf_routed.json
FILENAME_FASM    = ro_puf.fasm

nextpnr-xilinx -l nextpnr.log --chipdb $(CHIPDB) --xdc $(XDC) --json $(FILENAME_NETLIST)  --write $(FILENAME_ROUTED) --fasm $(FILENAME_FASM) --router router1


# ------------------------------------------------------------
# Process the JSON in Nextpnr-Xilinx to create FASM file



